version: '3.8'

services:
  pentest-env:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ..:/workspace:cached # Monta o diretório do projeto (pai de docker/) dentro do contêiner
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true # Necessário para OpenVPN em alguns casos
    working_dir: /workspace

  

